apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
stringData:
  MYSQL_USER: "app_user"
data:
  01-init.sql: |
    CREATE DATABASE IF NOT EXISTS mobility_db;
    CREATE DATABASE IF NOT EXISTS metabase_db;
    GRANT ALL PRIVILEGES ON mobility_db.* TO 'app_user'@'%';
    GRANT ALL PRIVILEGES ON metabase_db.* TO 'app_user'@'%';
    FLUSH PRIVILEGES;
  02-init.sh: |
    #!/bin/bash
    if [ -f "/tmp/data/google-mobility.sql.gz" ]; then
    echo "Iniciando importación del dataset de movilidad..."
    zcat /tmp/data/google-mobility.sql.gz | mysql -u root -p"$MYSQL_ROOT_PASSWORD" mobility_db
    echo "Importación completada con éxito."
    else
    echo "Error: No se encontró el archivo del dataset descargado."
    fi