apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
      - name: download-dataset
        image: alpine:latest
        command:
        - sh
        - -c
        - |
          echo "Descargando dataset desde GitHub..."
          wget -qO /tmp/data/google-mobility.sql.gz "https://raw.githubusercontent.com/FrancoQuiroga/CasoEstudio3Teleinf/main/data/google-mobility.sql.gz"
        volumeMounts:
        - name: shared-data
          mountPath: /tmp/data
      #que paso acá?, Había que asignar un número de recursos (No sé si es necesario)
      containers:
      - name: mysql
        image: mysql:8.0
        resources:
        # Ponemos como mínimo 1Gbi de memoria y 1 vcpu. Y como máximo el doble
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"
        envFrom:
          - configMapRef:
              name: mysql-init-script

        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
               secretKeyRef:
                 name: db-secrets
                 key: mysql_root_password
          - name: MB_DB_PASS
            valueFrom: 
               secretKeyRef:
                 name: db-secrets
                 key: mysqlpassword
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d

      
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-persistent-vc
      - name: init-script
        configMap:
          name: mysql-init-script
      - name: shared-data
        emptyDir: {} 