apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-vc3
  namespace: fequirogaa-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi