apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  namespace: fequirogaa-dev
spec:
  serviceName: mysql-service
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
      - name: download-dataset
        image: alpine:latest
        command:
        - sh
        - -c
        - |
          echo "Descargando dataset desde GitHub..."
          wget -qO /tmp/data/google-mobility.sql.gz "https://raw.githubusercontent.com/FrancoQuiroga/CasoEstudio3Teleinf/main/data/google-mobility.sql.gz"
        volumeMounts:
        - name: shared-data
          mountPath: /tmp/data
      containers:
      - name: mysql
        image: mysql:8.0
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"
        envFrom:
          - configMapRef:
              name: mysql-init-script
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
               secretKeyRef:
                 name: db-secrets
                 key: mysql_root_password
          - name: MYSQL_PASSWORD
            valueFrom:
               secretKeyRef:
                 name: db-secrets
                 key: mysqlpassword
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        - name: shared-data
          mountPath: /tmp/data

      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-persistent-vc3
      - name: init-script
        configMap:
          name: mysql-init-script
      - name: shared-data
        emptyDir: {}
